/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoolife.ventanas;

//Importar clases

import zoolife.Cliente;

/**
 *
 * @author Benjamín Igor 
 * @author Emilio Contreras 
 * @author Pablo Martínez
 */
public class JDonatorio extends javax.swing.JFrame {

    /**
     * Creates new form JDonatorio
     */
    
    //Instanciar
    
    Cliente cliente;
    
    //Declaración de variables
    
    private int total;
    
    //Constructor
    
    public JDonatorio(Cliente cliente, int total) {
        this.cliente = cliente;
        this.total = total;
        initComponents();
        this.Jtotal.setText("$" + String.valueOf(total));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCancelar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boxAnimales = new javax.swing.JComboBox<>();
        Apadrinar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jtotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCancelar2.setText("Volver");
        jCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Qué animal desea apadrinar?");

        boxAnimales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Panda Rojo", "Cocodrilo", "Lémur", "Rinoceronte", "Jirafa" }));
        boxAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAnimalesActionPerformed(evt);
            }
        });

        Apadrinar.setText("Apadrinar");
        Apadrinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApadrinarActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        jLabel3.setText("El costo para apadrinar un animal es de $25000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Apadrinar)
                    .addComponent(boxAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(Jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelar2)
                    .addComponent(Apadrinar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botones
    private void jCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelar2ActionPerformed
        /**Llamar ventana
         * Traspasar datos
         */
        JMenu menu = new JMenu(cliente, total);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCancelar2ActionPerformed

    private void boxAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAnimalesActionPerformed
        
    }//GEN-LAST:event_boxAnimalesActionPerformed

    private void ApadrinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApadrinarActionPerformed
        /**Seleccionar articulo
         * Sumar el valor
         */
        String articulo = boxAnimales.getSelectedItem().toString();
        total += 25000;
        this.Jtotal.setText("$" + String.valueOf(total));
        
    }//GEN-LAST:event_ApadrinarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apadrinar;
    private javax.swing.JLabel Jtotal;
    private javax.swing.JComboBox<String> boxAnimales;
    private javax.swing.JButton jCancelar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
