/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoolife.ventanas;

//Importar clases

import zoolife.Cliente;
import zoolife.Gorro;
import zoolife.Llavero;
import zoolife.Mascarilla;
import zoolife.Peluche;

/**
 *
 * @author Benjamín Igor 
 * @author Emilio Contreras 
 * @author Pablo Martínez
 */
public class JTienda extends javax.swing.JFrame {

    /**
     * Creates new form JTienda
     */
    
    //Instanciar
    
    Cliente cliente;
    
    //Crear los objetos
    
    Mascarilla mascarilla = new Mascarilla("Mascarilla", 1000);
    Gorro gorro = new Gorro("Gorro", 2000);
    Llavero llavero = new Llavero("Llavero", 1000);
    Peluche peluche = new Peluche("Peluche", 4800);
    
    //Declarar varibles
    
    private int costo;
    private int total;

    //Constructor
    
    public JTienda(Cliente cliente, int total) {
        this.cliente = cliente;
        this.total = total;
        initComponents();
        this.Jtotal.setText("$" + String.valueOf(total));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jtotal = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        boxArticulo = new javax.swing.JComboBox<>();
        Quitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSalir1.setText("Volver");
        jSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalir1ActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Qué desea comprar?");

        jLabel6.setText("Total");

        jLabel7.setText("Cantidad:");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        boxArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peluche ($4800)", "Gorro ($2000)", "Llavero ($1000)", "Mascarilla ($1000)" }));

        Quitar.setText("Quitar");
        Quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(38, 38, 38)
                        .addComponent(Jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(boxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quitar)
                    .addComponent(Agregar)
                    .addComponent(jSalir1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botones
    private void jSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalir1ActionPerformed
        JMenu menu = new JMenu(cliente, total);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jSalir1ActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
       /**Seleccionar articulo
        * Determinar cantidad
        * Multiplicar por valor corresponiente
        * Sumar al total
        */
          
        String articulo = boxArticulo.getSelectedItem().toString();
        int cantidad = Integer.parseInt(this.Cantidad.getText());
        if (articulo.equals("Peluche ($4800)")) {
            total += cantidad * peluche.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Gorro ($2000)")) {
            total += cantidad * gorro.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Llavero ($1000)")) {
            total += cantidad * llavero.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Mascarilla ($1000)")) {
            total += cantidad * mascarilla.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void QuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarActionPerformed
       /**Seleccionar articulo
        * Determinar cantidad
        * Multiplicar por valor corresponiente
        * Restar al total
        */ 
       
        String articulo = boxArticulo.getSelectedItem().toString();
        int cantidad = Integer.parseInt(this.Cantidad.getText());
        //"Peluche ($4800)", "Gorro ($2000)", "Llavero ($1000)", "Mascarilla ($1000)"
        if (articulo.equals("Peluche ($4800)")) {
            total -= cantidad * peluche.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Gorro ($2000)")) {
            total -= cantidad * gorro.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Llavero ($1000)")) {
            total -= cantidad * llavero.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        if (articulo.equals("Mascarilla ($1000)")) {
            total -= cantidad * mascarilla.getValor();
            this.Jtotal.setText("$" + String.valueOf(total));
        }
        
    }//GEN-LAST:event_QuitarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JLabel Jtotal;
    private javax.swing.JButton Quitar;
    private javax.swing.JComboBox<String> boxArticulo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jSalir1;
    // End of variables declaration//GEN-END:variables
}
